"""Write the CH2NH2 cc-pVTZ S0/S1 MECI geometries as a LaTeX longtable.

Reads the converged ``*_optimized.xyz`` of each method's MECI run and emits one
table in the style of ``test/supporting_information_geometries.tex``.  No quantum
chemistry is re-run and no coordinate is retyped: the runs come from
``ch2nh2_meci_geometry_descriptors.GEOMETRY_SPECS``, so the table and the
descriptor table can never disagree about which geometry belongs to which method.

The default selection is the three methods compared in the manuscript figure --
CASCI, GBCI with the occupation grouping, and SA-CASSCF.  The ungrouped GBCI run
is available through ``--labels``.

Usage::

    python make_meci_geometry_table.py
    python make_meci_geometry_table.py --labels "CASCI,GBCI (nogroup)"
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from utils.geometry_descriptors import read_xyz  # noqa: E402

from ch2nh2_meci_geometry_descriptors import GEOMETRY_SPECS  # noqa: E402

DEFAULT_OUTPUT = SCRIPT_DIR / "outputs" / "ch2nh2_ccpvtz_meci_geometries.tex"

# Methods in the order they appear in the manuscript figure, and how each should be
# named in the table.  The keys are GEOMETRY_SPECS labels; the values are the LaTeX
# row headings.  CASSCF is state-averaged over S0 and S1 with equal weights
# (ch2nh2_casscf_S0S1_meci_5o8e_ccpvtz.py: NROOTS = 2, STATE_WEIGHTS = [0.5, 0.5]),
# so it is labelled SA-CASSCF here.
DEFAULT_LABELS = ("CASCI", "GBCI (groupocc)", "CASSCF")
ROW_HEADINGS = {
    "CASCI": r"CASCI(8e,5o)/cc-pVTZ",
    "GBCI (groupocc)": r"GBCI(8e,5o)/cc-pVTZ",
    "GBCI (nogroup)": r"GBCI(8e,5o)/cc-pVTZ, no grouping",
    "CASSCF": r"SA-CASSCF(8e,5o)/cc-pVTZ",
}

CAPTION = (
    r"Optimized Cartesian coordinates (\AA) of the CH$_2$NH$_2^+$ "
    r"S$_0$/S$_1$ minimum-energy conical intersections located with CASCI, GBCI "
    r"and SA-CASSCF in the (8e,5o) active space with the cc-pVTZ basis."
)
LABEL = "tab:si_ch2nh2_ccpvtz_meci_geometries"


def optimized_xyz(spec: dict) -> Path:
    """Path of a spec's converged geometry.

    The run directory and the file share a stem, which is the repository convention
    for these outputs and what ch2nh2_meci_geometry_descriptors.py relies on too.
    """
    run_dir = (SCRIPT_DIR / spec["run_dir"]).resolve()
    return run_dir / f"{run_dir.name}_optimized.xyz"


def table(labels, specs_by_label: dict) -> str:
    lines = [
        r"% CH2NH2+ cc-pVTZ S0/S1 MECI geometries, Cartesian coordinates in Angstrom.",
        r"% Generated by test/ch2nh2/analysis/make_meci_geometry_table.py",
        r"% Requires: \usepackage{longtable}",
        r"\begin{longtable}{llrrr}",
        rf"\caption{{{CAPTION}}}\label{{{LABEL}}}\\",
        r"\hline",
        r"Method & Atom & $x$ & $y$ & $z$ \\",
        r"\hline",
        r"\endfirsthead",
        r"\hline",
        r"Method & Atom & $x$ & $y$ & $z$ \\",
        r"\hline",
        r"\endhead",
        r"\hline",
        r"\endfoot",
    ]
    for label in labels:
        spec = specs_by_label[label]
        path = optimized_xyz(spec)
        symbols, coords = read_xyz(path)
        heading = ROW_HEADINGS.get(label, label)
        lines.append(rf"\multicolumn{{5}}{{l}}{{\textbf{{{heading}}}}}\\")
        for symbol, (x, y, z) in zip(symbols, coords):
            lines.append(f" & {symbol} & {x:11.8f} & {y:11.8f} & {z:11.8f} " + r"\\")
    lines.append(r"\end{longtable}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--labels", default=",".join(DEFAULT_LABELS),
                        help="comma-separated GEOMETRY_SPECS labels, in table order")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    specs_by_label = {spec["label"]: spec for spec in GEOMETRY_SPECS}
    labels = [label.strip() for label in args.labels.split(",") if label.strip()]
    unknown = [label for label in labels if label not in specs_by_label]
    if unknown:
        raise SystemExit(f"unknown labels {unknown}; "
                         f"available: {sorted(specs_by_label)}")

    text = table(labels, specs_by_label)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    for label in labels:
        print(f"{label:<18} {optimized_xyz(specs_by_label[label])}")
    print(f"-> {args.output}")


if __name__ == "__main__":
    main()
